<?php
/**
 * Opcache warm-up file generated by Composer Preload plugin.
 * This file was generated automatically. Any changes will be overwritten
 * during the next "composer preload" command.
 */
error_reporting(E_ALL);
if (!function_exists('opcache_compile_file') || !ini_get('opcache.enable')) {
    echo 'Opcache is not available.';
    die(1);
}

if ('cli' === PHP_SAPI && !ini_get('opcache.enable_cli')) {
    echo 'Opcache is not enabled for CLI applications.';
    die(2);
}
//preloadarray

foreach ($filesList as $key => $value) {
    opcache_compile_file($value);
}
